version: '3.1'

services:
        api:
                build: api
                container_name: api
                ports:
                        - 8888:8888
                environment:
                        - DB_HOST=192.168.52.80
                        - DB_PORT=5432
                        - DB_NAME=NSI
                        - DB_USER=user1c
                        - DB_USER_PASS=sGLaVj4PUw

