version: '3.1'

services:
        api:
                build: api
                container_name: api
                ports:
                        - 8888:8888
                environment:
                        - DB_HOST=10.10.10.127
                        - DB_PORT=5432
                        - DB_NAME=mdm
                        - DB_USER=postgres
                        - DB_USER_PASS=123

